image: silex/emacs:master-alpine-ci

stages:
  - publish

.publish: &publish
  script:
  - make publish
  cache:
    paths:
      - .packages/
      - .timestamps/
      - public
    policy: pull-push

pages:
  stage: publish
  <<: *publish
  only:
  - master
