image: silex/emacs:master-alpine-ci

stages: 
  - publish

.publish: &publish
#  script:
#    - apk add --update --no-cache python3
#    - make publish
#  cache:
#    paths:
#      - .packages/
#      - .timestamps/
#      - public/
#    policy: pull-push
  artifacts:
    paths:
    - public/

pages:
  stage: publish
  <<: *publish
  only:
  - master
