image: silex/emacs:master-alpine-ci

stages:
  - publish

.publish: &publish
  script:
  - make publish
  artifacts:
    paths:
    - public

pages:
  stage: publish
  <<: *publish
  only:
  - master
