image: silex/emacs:master-alpine-ci

stages:
  - publish

.publish: &publish
  script:
  - make publish
  artifacts:
    paths:
    - public

pages:
  stage: publish
  <<: *publish
  only:
  - master
  environment:
    name: writepermission.com
    url: https://writepermission.com

pages:preview:
  stage: publish
  <<: *publish
  except:
  - master
  environment:
    name: preview/$CI_COMMIT_REF_NAME
    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html
