image: silex/emacs:master-alpine-ci

stages:
  - setup
  - publish

setup:
  script:
    - apk add --update --no-cache python3
  cache:
    paths:
      - /usr/bin/python3

.publish: &publish
  script:
  - make publish
  cache:
    paths:
      - .packages/
      - .timestamps/
    policy: pull-push
  artifacts:
    paths:
    - public

pages:
  stage: publish
  <<: *publish
  only:
  - master
