#+TITLE: Announcing gross.css v3.0.0
#+DATE: <2030-12-31 Tue>

** Gross.css v3.0.0

I'm proud to announce [[http://to1ne.gitlab.io/gross.css][gross.css]] v3.0.0. It's a huge release because it
is 500% more gross, but more on that later.

The most exciting feature is probably "dark mode", although it the topic was a
lot hotter when I started at it.

** Stacking Cartons

Gross.css v3.0.0 has codename Stacking Cartons, and there is a very good reason
for this...

When I was implementing dark mode, I didn't want to abandon light mode, so I
wanted to support both. I could haven chose to provide two css files: one for
light and one for dark. But for light mode a lot less statements are needed, so
it would be impossible to provide feature parity in both modes. So I decided to
extract only the /dark/ part into a separate css file.

But how would users be able to chose between dark mode or light mode?

I built the concept stacking css files. Each css file will include another css
file in a subdirectory. That file can include yet another css file, two levels
deep, etc.

So the directory tree will look like this:

#+begin_src sh
css
├── carton
│   ├── carton
│   │   ├── carton
│   │   │   └── gross.css
│   │   └── gross.css
│   └── gross.css
└── gross.css
#+end_src

This means each css file needs to have a ~@import~ statement to include the css
file in a subdir:

#+begin_src css
@import 'carton/gross.css';
#+end_src

The naming is fixed ~carton~ for the directory and ~gross.css~ for the css
file.

There's an analogy with real life egg cartons here. Assume you have a bunch of
eggs, you can lay a carton on top of it, which again can fit again a bunch of
eggs, and again...

On the [[http://to1ne.gitlab.io/gross.css/demo/index.html][demo page]] you can get a sense of how the cartons stack. I've placed the
demo page in each carton, and with the two links at the top of the page you can
take one carton less or more carton more. By default the cartons are stacked so
the most essential come first, and you'll notice this quickly when the base
~gross.css~ is dropped first.

*** More cartons

The technique of stacking cartons allowed me to not only extract dark mode into
a carton, but I've also extracted table styles in a carton. This way I could
focus typography in the base gross.css and make table styles even better in it's
separate carton. In the end, these are the cartons I'm introducing in this
release

- ~dark~ :: Dark mode!!
- ~forms~ :: Make html forms better looking.
- ~other~ :: Style html tags like ~<blockquote>~ and ... TODO
- ~tables~ :: Better looking tables, with horizontal scrollbar if needed.
- ~version~ :: Defines two classes that will insert the gross.css version and
  codename.

You could say introducing cartons is cheating the 144 characters rule,
but I don't agree for two reasons:

- In the 144 characters the ~@import~ statement is included. So I'm
  losing 27 characters in each css file on that.
- The base ~gross.css~ file still perfectly usable on its own, without any
  carton.
- Each carton is functional on its own as well. If you only want to use the dark
  carton, that's perfectly fine.
